/* tslint:disable */
/* eslint-disable */
/**
 * Weather API
 * API provides access to summarized weather data parsed from the UK MetOffice.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * Climate Record Serializer
 * @export
 * @interface ClimateRecord
 */
export interface ClimateRecord {
    /**
     * 
     * @type {number}
     * @memberof ClimateRecord
     */
    'id': number;
    /**
     * 
     * @type {DatasetEnum}
     * @memberof ClimateRecord
     */
    'dataset': DatasetEnum;
    /**
     * 
     * @type {number}
     * @memberof ClimateRecord
     */
    'year': number;
    /**
     * 
     * @type {number}
     * @memberof ClimateRecord
     */
    'jan'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ClimateRecord
     */
    'feb'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ClimateRecord
     */
    'mar'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ClimateRecord
     */
    'apr'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ClimateRecord
     */
    'may'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ClimateRecord
     */
    'jun'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ClimateRecord
     */
    'jul'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ClimateRecord
     */
    'aug'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ClimateRecord
     */
    'sep'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ClimateRecord
     */
    'oct'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ClimateRecord
     */
    'nov'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ClimateRecord
     */
    'dec'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ClimateRecord
     */
    'win'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ClimateRecord
     */
    'spr'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ClimateRecord
     */
    'sum'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ClimateRecord
     */
    'aut'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ClimateRecord
     */
    'ann'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ClimateRecord
     */
    'created_on': string;
    /**
     * 
     * @type {string}
     * @memberof ClimateRecord
     */
    'updated_on': string;
}


/**
 * * `air_frost` - Air Frost * `raindays` - Rain Days ≥1mm * `rainfall` - Rainfall * `sunshine` - Sunshine * `tmean` - Mean Temperature * `tmin` - Minimum Temperature * `tmax` - Maximum Temperature
 * @export
 * @enum {string}
 */

export const DatasetEnum = {
    AirFrost: 'air_frost',
    Raindays: 'raindays',
    Rainfall: 'rainfall',
    Sunshine: 'sunshine',
    Tmean: 'tmean',
    Tmin: 'tmin',
    Tmax: 'tmax'
} as const;

export type DatasetEnum = typeof DatasetEnum[keyof typeof DatasetEnum];


/**
 * 
 * @export
 * @interface PaginatedClimateRecordList
 */
export interface PaginatedClimateRecordList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedClimateRecordList
     */
    'count': number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedClimateRecordList
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedClimateRecordList
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<ClimateRecord>}
     * @memberof PaginatedClimateRecordList
     */
    'results': Array<ClimateRecord>;
}

/**
 * ClimateApi - axios parameter creator
 * @export
 */
export const ClimateApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Climate Record ViewSet
         * @param {string} [dataset] 
         * @param {number} [limit] Number of results to return per page.
         * @param {number} [offset] The initial index from which to return the results.
         * @param {number} [year] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        climateList: async (dataset?: string, limit?: number, offset?: number, year?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/climate/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication cookieAuth required

            if (dataset !== undefined) {
                localVarQueryParameter['dataset'] = dataset;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (year !== undefined) {
                localVarQueryParameter['year'] = year;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Climate Record ViewSet
         * @param {number} id A unique integer value identifying this climate record.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        climateRetrieve: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('climateRetrieve', 'id', id)
            const localVarPath = `/api/climate/{id}/`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication cookieAuth required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ClimateApi - functional programming interface
 * @export
 */
export const ClimateApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ClimateApiAxiosParamCreator(configuration)
    return {
        /**
         * Climate Record ViewSet
         * @param {string} [dataset] 
         * @param {number} [limit] Number of results to return per page.
         * @param {number} [offset] The initial index from which to return the results.
         * @param {number} [year] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async climateList(dataset?: string, limit?: number, offset?: number, year?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedClimateRecordList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.climateList(dataset, limit, offset, year, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClimateApi.climateList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Climate Record ViewSet
         * @param {number} id A unique integer value identifying this climate record.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async climateRetrieve(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ClimateRecord>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.climateRetrieve(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClimateApi.climateRetrieve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ClimateApi - factory interface
 * @export
 */
export const ClimateApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ClimateApiFp(configuration)
    return {
        /**
         * Climate Record ViewSet
         * @param {string} [dataset] 
         * @param {number} [limit] Number of results to return per page.
         * @param {number} [offset] The initial index from which to return the results.
         * @param {number} [year] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        climateList(dataset?: string, limit?: number, offset?: number, year?: number, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedClimateRecordList> {
            return localVarFp.climateList(dataset, limit, offset, year, options).then((request) => request(axios, basePath));
        },
        /**
         * Climate Record ViewSet
         * @param {number} id A unique integer value identifying this climate record.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        climateRetrieve(id: number, options?: RawAxiosRequestConfig): AxiosPromise<ClimateRecord> {
            return localVarFp.climateRetrieve(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ClimateApi - object-oriented interface
 * @export
 * @class ClimateApi
 * @extends {BaseAPI}
 */
export class ClimateApi extends BaseAPI {
    /**
     * Climate Record ViewSet
     * @param {string} [dataset] 
     * @param {number} [limit] Number of results to return per page.
     * @param {number} [offset] The initial index from which to return the results.
     * @param {number} [year] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClimateApi
     */
    public climateList(dataset?: string, limit?: number, offset?: number, year?: number, options?: RawAxiosRequestConfig) {
        return ClimateApiFp(this.configuration).climateList(dataset, limit, offset, year, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Climate Record ViewSet
     * @param {number} id A unique integer value identifying this climate record.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClimateApi
     */
    public climateRetrieve(id: number, options?: RawAxiosRequestConfig) {
        return ClimateApiFp(this.configuration).climateRetrieve(id, options).then((request) => request(this.axios, this.basePath));
    }
}



